apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment-jenkins
  namespace: taojianglong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
         app: helloworld
    spec:
      containers:
        - name: helloworld
          image: go-web-server
          ports:
            - containerPort: 8082
