apiVersion: v1
kind: Service
metadata:
  name: helloworld-svc-jenkins
  namespace: taojianglong
  labels:
    app: helloworld-jenkins
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8082
    protocol: TCP
  selector:
    app: helloworld-jenkins
